name: geo_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - xarray
  - dask
  - dash
  - scipy
  - statsmodels
  - geopandas
  - rasterio
  - rioxarray
  - shapely
  - pyproj
  - boto3
  - requests
  - urllib3
  - matplotlib
  - plotly
  - folium
  - python-dotenv
  - pip
  - pip:
      - pystac
      - pystac-client
      - odc-stac

